import { Inter } from "next/font/google";
import "./globals.css";
import { Quicksand } from "next/font/google";
import { Bebas_Neue } from "next/font/google";

import ProviderClient from "./provider";
import { ReactNode } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-quicksand",
});

const bebasNeue = Bebas_Neue({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-bebas-neue",
});

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} ${bebasNeue.variable}`}>
        <ProviderClient>{children}</ProviderClient>
      </body>
    </html>
  );
}
