import { Poppins, Shadows_Into_Light,Montserrat,Open_Sans, Lato } from "next/font/google";
import "./globals.css";
import { Quicksand } from "next/font/google";

import ProviderClient from "./provider";
import { ReactNode } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-quicksand",
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});


const shadowsIntoLight = Shadows_Into_Light({
  weight: '400',
  subsets: ["latin"],
  variable: "--font-shadows_into_light",
});


export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable}  ${shadowsIntoLight.variable} ${lato.className}`}>
        <ProviderClient>{children}</ProviderClient>
      </body>
    </html>
  );
}
