import { Inter } from "next/font/google";
import "./globals.css";
import { Quicksand } from "next/font/google";
import ProviderClient from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700']
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        <main>
          <ProviderClient>
            {children}
          </ProviderClient>
        </main>
      </body>
    </html>
  );
}
